### ISSUE TITLE
Mouse mode

### ISSUE THREAD

**Issue by confluencepoint** [fabiomcosta/dotfiles#3]
https://github.com/fabiomcosta/dotfiles/blob/main/home/.config/karabiner.edn#L83-L102

How does the mouse mode work?
Can you explain this please?

**Comment by fabiomcosta** [comment]
Hi @confluencepoint,
It starts with this declaration: https://github.com/fabiomcosta/dotfiles/blob/main/home/.config/karabiner.edn#L61
So when I press and hold 'a', :mouse_mode is set, and because this is declared under "symlayers" I have to quickly press any other key that is defined under mouse_mode for them to actually work.

Ex: press `a` then quickly press `j`, now the cursor should go down
keep `a` pressed and press `k` and the cursor goes up, and so on...

Does this answer your question or were you asking about something else?

**Comment by fabiomcosta** [comment]
Closing, feel free to re-open if needed.
